import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { Toaster } from "@/components/ui/sonner"
import MySessionProvider from "./_Provider/MySessionProvider";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MySessionProvider>
         <ThemeProvider>
          {children}
          <Toaster />
          </ThemeProvider>
          </MySessionProvider>
      </body>
    </html>
  );
}
